name: RTx-AuthTool
version: 0.01
abstract: Web authentication tools
author: Autrijus Tang <autrijus@autrijus.org>
license: perl
distribution_type: module
no_index:
  directory:
    - html
    - po
    - inc
generated_by: Module::Install version 0.35
